In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('DatasetDocBot_final.csv')
data.head(15)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0        Alam                                0                 1   
1       Kadir                                1                 0   
2       Farid                                1                 0   
3       Rahim                                0                 0   
4      Barsha                                0                 0   
5       Rifah                                0                 0   
6     Mashrar                                1                 0   
7   Oporajita                                0                 0   
8      Saliha                                0                 0   
9         eva                                0                 0   
10      karim                                0                 0   
11      kadir                                0                 0   
12      Rafiq                                0                 0   
13     Robiul                                0                 1   
14      Afrah                                0                 0   

    Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                   0                  0        0                        0   
1                   0                  0        0                        0   
2                   0                  0        0                        0   
3                   0                  1        0                        0   
4                   0                  0        1                        0   
5                   0                  0        1                        0   
6                   0                  0        0                        0   
7                   0                  0        0                        1   
8                   0                  1        0                        0   
9                   0                  0        0                        0   
10                  0                  1        0                        0   
11                  1                  1        0                        0   
12                  0                  0        1                        0   
13                  0                  1        0                        0   
14                  0                  1        0                        0   

    Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                           0              0                           1  ...   
1                           1              1                           0  ...   
2                           1              0                           1  ...   
3                           0              0                           1  ...   
4                           0              0                           1  ...   
5                           0              0                           0  ...   
6                           0              0                           1  ...   
7                           0              0                           1  ...   
8                           0              0                           0  ...   
9                           1              0                           1  ...   
10                          0              0                           0  ...   
11                          0              0                           1  ...   
12                          0              0                           0  ...   
13                          0              0                           1  ...   
14                          0              0                           0  ...   

    Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0           1       0                     0                     0   
1           1       1                     1                     0   
2           0       1                     0                     1   
3           1       0                     0                     0   
4           0       0    

In [3]:
len(data.columns)

21

In [4]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe
X = data.iloc[:,1:20].values
y = data.iloc[:,20].values

In [5]:
X[250]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [6]:
y

array(['Oculer hypertension', 'Catracts', 'Catracts', 'Bulgy Vision',
       'Glaucoma ACG', 'Glaucoma ACG', 'Catracts', 'Congenital Glaucoma',
       'Bulgy Vision', 'Glaucoma ACG', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertensio

In [7]:
from sklearn.svm import SVC
model = SVC(kernel='linear', random_state = 0)
model.fit(X,y) 

SVC(kernel='linear', random_state=0)

In [8]:
from sklearn.model_selection import KFold
n_splits=10
kf = KFold(n_splits=n_splits,random_state=0, shuffle=True)

In [9]:
from sklearn.model_selection import cross_val_score
results = cross_val_score(model,X,y,cv=kf)
results

array([0.94736842, 0.96491228, 0.98245614, 0.94642857, 0.94642857,
       1.        , 0.92857143, 0.91071429, 0.98214286, 1.        ])

In [10]:
results.mean() # Accuracy

0.9609022556390977

In [11]:
print("Accuracy: %.3f%% (%.3f%%)"% (results.mean()*100.0, results.std()*100.0))

Accuracy: 96.090% (2.856%)


In [12]:
from sklearn.metrics import confusion_matrix, classification_report

for train_index, val_index in kf.split(X):
    model.fit(X[train_index], y[train_index])
    pred = model.predict(X[val_index])
    print(confusion_matrix(y[val_index], pred))
    print(classification_report(y[val_index], pred))

[[ 1  0  0  0  0  0]
 [ 3  0  0  0  0  0]
 [ 0  0 27  0  0  0]
 [ 0  0  0  7  0  0]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  0 12]]
                     precision    recall  f1-score   support

       Bulgy Vision       0.25      1.00      0.40         1
       Bulgy Vision       0.00      0.00      0.00         3
           Catracts       1.00      1.00      1.00        27
Congenital Glaucoma       1.00      1.00      1.00         7
       Glaucoma ACG       1.00      1.00      1.00         7
Oculer hypertension       1.00      1.00      1.00        12

           accuracy                           0.95        57
          macro avg       0.71      0.83      0.73        57
       weighted avg       0.93      0.95      0.94        57

[[ 2  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  0 21  0  0  0]
 [ 0  0  0  8  0  1]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  0 16]]
                     precision    recall  f1-score   support

       Bulgy Vision       0.67      1.00      0.80         2
       Bul

C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\U

In [13]:
def predictDisease(array19):
    return model.predict([array19])[0]

In [14]:
print(predictDisease([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0]));

Congenital Glaucoma


In [17]:
import pickle
with open('DocbotEyeDiseasePredictor_SVM_model.pickle','wb') as f:
    pickle.dump(model,f)

In [18]:
import json
columns={
    'data_columns':[col.lower() for col in data.columns]
}
with open("all_columns.json","w") as f:
    f.write(json.dumps(columns))